name: Publish package to the Maven Central Repository
#on:
#  release:
#    types: [created]
on:
  push:
    branches: [ releases ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
#      - name: Debug true
#        env:
#         MAVEN_USERNAME: ${{ secrets.REPO_LOGIN }}
#         MAVEN_PASSWORD: ${{ secrets.REPO_PWD }}
#        if: ${{env.MAVEN_USERNAME}} == 'mihaita.tinta'
#        run: |
#          echo "username found "
#      - name: Debug false
#        env:
#          MAVEN_USERNAME: ${{ secrets.REPO_LOGIN }}
#          MAVEN_PASSWORD: ${{ secrets.REPO_PWD }}
#        if: ${{env.MAVEN_USERNAME}} == 'asdasda'
#        run: |
#          echo "username not found "
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.REPO_LOGIN }}
          MAVEN_PASSWORD: ${{ secrets.REPO_PWD }}
        run: mvn install deploy -Drepo.login=$MAVEN_USERNAME -Drepo.pwd=$MAVEN_PASSWORD
