name: Publish package to the Maven Central Repository
on:
  push:
    branches: [ releases ]
  pull_request:
    types: [closed]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Debug
        env:
          MAVEN_USERNAME: ${{ secrets.REPO_LOGIN }}
        run: |
          cat /home/runner/.m2/settings.xml
          echo "username is: "
          echo ${{secrets.REPO_LOGIN}} | sed 's/./& /g'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.REPO_LOGIN }}
          MAVEN_PASSWORD: ${{ secrets.REPO_PWD }}
